/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com
 @idle games : http://www.gityx.com
 @QQ Group : 627141737

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    "points": "点数",
    "Reset for +": "重置得到 + ",
    "Currently": "当前",
    "Effect": "效果",
    "Cost": "成本",
    "Goal:": "目标:",
    "Reward": "奖励",
    "Start": "开始",
    "Exit Early": "提前退出",
    "Finish": "完成",
    "Milestone Gotten!": "获得里程碑！",
    "Milestones": "里程碑",
    "Completed": "已完成",
    "Default Save": "默认存档",
    "Delete": "删除",
    "No": "否",
    "Saves": "存档",
    "Options": "选项",
    "Yes": "是",
    "Are you sure?": "你确定吗？",
    "Edit Name": "编辑名称",
    "Info": "信息",
    "Currently:": "当前:",
    "Appearance": "外观",
    "How the game looks.": "游戏看起来如何。",
    "Theme": "主题",
    "Show milestones": "显示里程碑",
    "Show TPS meter at the bottom-left corner of the page.": "在页面左下角显示 TPS。",
    "Show TPS": "显示 TPS",
    "None": "无",
    "Align modifier units": "对齐概览单位",
    "Align numbers to the beginning of the unit in modifier view.": "在概览视图中将数字与单元的开头对齐。",
    "Select which milestones to display based on criterias.": "根据标准选择要显示的里程碑。",
    "All": "全部",
    "Classic": "经典",
    "Configurable": "可配置",
    "Duplicate": "复制",
    "Mute": "静音",
    "Unmute": "播放",
    "Join the Discord!": "加入 Discord!",
    "Price:": "价格:",
    "Home": "首页",
    "How to Play Wordle": "如何玩字兜",
    "Login attempts:": "登录尝试次数：",
    "Practice History": "练习历史",
    "Printer": "打印机",
    "Printing Mogul": "印刷大亨",
    "Printing Press": "印刷机",
    "Owned upgrades": "拥有的升级",
    "Efficiency:": "效率:",
    "Export Save File": "导出存档文件",
    "Import Save File": "导入存档文件",
    "Export/Import Save Text": "导出/导入 存档文本",
    "Export Save Text": "导出 存档文本",
    "Import Save Text": "导入 存档文本",
    "Final Value": "最终价值",
    "First Steps": "第一步",
    "Game Over!": "游戏结束!",
    "Game Settings": "游戏设置",
    "Base Value": "基础价值",
    "Bank:": "银行:",
    "Balance: $": "余额: $",
    "Best WPM": "最佳每分钟单词数",
    "Building": "建筑",
    "Building Upgrades": "建筑升级",
    "Buy": "购买",
    "Buy:": "购买:",
    "Doubles production from Printers.": "打印机 产量翻倍。",
    "Doubles production from Stock Market.": "股票市场 产量翻倍。",
    "Doubles production from Typing Guild.": "打字公会 产量翻倍。",
    "Doubles production from Server Farms.": "服务器农场 产量翻倍。",
    "Triples production from Printers.": "打印机 产量翻3倍。",
    "Triples production from Stock Market.": "股票市场 产量翻3倍。",
    "Triples production from Typing Guild.": "打字公会 产量翻3倍。",
    "Triples production from Server Farms.": "服务器农场 产量翻3倍。",
    "Triples production from IT Offices.": "IT办公室 产量翻3倍。",
    "Triples production from Cyber Cafes.": "网吧 产量翻3倍。",
    "our Guild": "你的公会",
    "Your Progress:": "你的进度:",
    "You can play again in:": "你可以再玩一次：",
    "You can hack again in:": "你可以再次入侵：",
    "WPM Boost:": "单词每分钟 提升:",
    "WPM": "单词每分钟",
    "Wordle Novice": "字兜新手",
    "Wordle Mastery": "字兜精通",
    "Wordle Master": "字兜大师",
    "Wordle Guild": "字兜公会",
    "Wordle Legend": "字兜传说",
    "Wordle Enthusiast": "字兜发烧友",
    "Wordle Challenge": "字兜挑战",
    "Typing Novice": "打字新手",
    "Typing Mastery": "打字精通",
    "Typing Master": "打字大师",
    "Typing Guild": "打字公会",
    "Typing Legend": "打字传说",
    "Typing Enthusiast": "打字发烧友",
    "Typing Challenge": "打字挑战",
    "Hard": "困难",
    "Very Hard": "非常困难",
    "Normal (~30 WPM)": "正常 (~30 单词每分钟)",
    "Very Hard (~90 WPM)": "非常困难 (~90 单词每分钟)",
    "Hard (~50 WPM)": "困难 (~50 单词每分钟)",
    "Username: Admin": "用户名: Admin",
    "Use your": "使用你的",
    "Upgrades": "升级",
    "Unknown Building": "未知建筑",
    "Typing test": "打字测试",
    "Try again": "再试一次",
    "TypeIdle": "打字放置",
    "TypeIdle.com - Typing Idle Game - ": "TypeIdle.com - 打字放置游戏 - ",
    "Type the words on enemies to help your tower defeat them.": "输入敌人身上的文字，帮助你的塔击败敌人。",
    "Per Level": "每级",
    "per second:": "每秒:",
    "Produced by buildings:": "由建筑生产：",
    "Produced by typing:": "由打字生产：",
    "Production Reports": "生产报告",
    "Production:": "生产:",
    "Qwerty Nordic": "北欧标准键盘",
    "Qwerty UK": "英国标准键盘",
    "Qwerty US": "美国标准键盘",
    "Race against AI": "与AI竞争",
    "Randomize Name": "随机名称",
    "Recent Trend": "近期趋势",
    "Research": "研究",
    "Research upgrades": "研究升级",
    "Research Lab": "研究实验室",
    "Research Pioneer": "研究先锋",
    "Research Points:": "研究点数:",
    "Reset Game Progress": "重置游戏进度",
    "Save Management": "保存管理",
    "Score:": "分数:",
    "Sell:": "出售:",
    "Sell": "出售",
    "Server Farm": "服务器农场",
    "Server Farm Lord": "服务器农场领主",
    "Skip words on mistake": "错误时跳过单词",
    "Slot Machine": "游戏机",
    "Slot Details": "游戏机详情",
    "Solve the Wordle to earn a boost!": "解决字兜以获得提升！",
    "Speed Demon": "速度之魔",
    "Spin to Win!": "转动以获胜！",
    "Spring Blossom": "春暖花开",
    "Start Hack": "开始入侵",
    "Stock Investor": "股票投资者",
    "Stock Market": "股票市场",
    "Stock Market Tycoon": "股票市场大亨",
    "Stocks": "股票",
    "Store": "商店",
    "Submit": "提交",
    "Tests Taken": "参加的测试",
    "Time left:": "剩余时间:",
    "Total Profit:": "总利润:",
    "Total:": "总计:",
    "Tower Destroyed!": "塔被摧毁了！",
    "Tower Health:": "塔生命值:",
    "Tower Upgrade": "塔升级",
    "Transaction History": "交易历史",
    "Improve your typing speed, unlock achievements, and upgrade buildings to boost your keystroke production!": "提高你的打字速度，解锁成就，并升级建筑物，以提高你的按键产量！",
    "IT Office": "IT办公室",
    "Keystroke Casino": "按键堵场",
    "Keystroke Tycoon": "按键大亨",
    "Keystroke layout": "按键布局",
    "Keystrokes": "按键",
    "Laser": "激光",
    "We use cookies to improve your experience and for traffic analysis. By using our site, you agree to our use of cookies.": "我们使用cookie来改善您的体验并进行流量分析。通过使用我们的网站，您同意我们使用cookie。",
    "Wordle": "字兜",
    "Achievement Hunter": "成就猎人",
    "Active Benefits": "活跃福利",
    "Adjust the game sound effects volume": "调整游戏音效音量",
    "Advanced IT Support": "高级IT支持",
    "Advanced research labs": "高级研究实验室",
    "Advanced Stock Trading Algorithms": "高级股票交易算法",
    "After Flat": "扁平之后",
    "AI Agent": "AI代理",
    "AI Typing Assistants": "AI打字助手",
    "Tower Defense": "塔防",
    "Arena Champion": "竞技场冠军",
    "Arena Guild": "竞技场公会",
    "Arena Legend": "竞技场传说",
    "Arena Challenger": "竞技场挑战者",
    "Artisanal Latte Workshop": "手工拿铁作坊",
    "Audio": "音频",
    "Automation Expert": "自动化专家",
    "Auto Writer": "自动作家",
    "Unlock 10 achievements.": "解锁 10 成就.",
    "Typing Arena": "打字竞技场",
    "Unlock new buildings and upgrades to boost your keystroke production!": "解锁新的建筑和升级，以提高你的按键生产！",
    "Triples production and research from research labs.": "使研究实验室的生产和研究增加3倍。",
    "Improves value of manually typed words.": "提高手动输入单词的价值。",
    "Initializing game...": "初始化游戏...",
    "Multiplier": "乘数",
    "Multiplier Modifiers": "乘数修饰符",
    "Automator": "自动器",
    "Achieve a WPM of 100.": "达到每分钟100个单词。",
    "Cyber Cafe Manager": "网吧经理",
    "Generate 100,000 keystrokes through buildings.": "通过建筑物产生 100,000 次按键。",
    "Beat normal opponent in the Arena.": "在竞技场中击败普通对手。",
    "Desert Sunset": "沙漠日落",
    "Defend the Tower": "保卫高塔",
    "Dark Coffee": "黑咖啡",
    "Doubles production from Cyber Cafes with a refined range of coffee blends.": "将网吧的产量翻倍，提供一系列精致的咖啡混合物。",
    "Doubles production from Cyber Cafes with a concentrated flow of caffeine.": "将网吧的产量翻倍，集中供应浓缩咖啡因",
    "Doubles production from Auto Writers and manually typed words.": "将自动作家和手动打字单词的产量翻倍。",
    "Enable 10 finger assist": "启用10指辅助",
    "Click on a golden news article.": "点击一篇黄金新闻文章。",
    "Elite Typing Guild": "精英打字公会",
    "Own 1 stock.": "持有1只股票。",
    "Make $100,000 profit with stocks.": "通过股票赚取 $100,000 的利润。",
    "Beat hard opponent in the Arena.": "在竞技场中击败对手。",
    "Beat very hard opponent in the Arena.": "在竞技场中击败非常强硬的对手。",
    "Golden Scoop": "金色勺子",
    "Own 10 Research Labs.": "拥有10个研究实验室。",
    "Overall Progress:": "总体进度:",
    "(guild name)": "(公会名称)",
    "(Work in progress)": "(开发中)",
    "Copy this text to backup your save or paste a save string to import": "复制此文本以备份您的存档或粘贴要导入的存档字符串",
    "Example: They decided to ***** a new house.": "例子:他们决定 ***** 一套新房子。",
    "Examples": "例子",
    "Generate Save Text": "生成存档字符串",
    "Gives you a break from typing.": "让你从打字中休息一下。",
    "Hint: construct (something) by putting parts or material together": "提示：通过将部件或材料放在一起来建造（某物）",
    "Danger Zone": "危险区",
    "Dark": "深色",
    "Each Produce": "每个生产",
    "Flat Modifiers": "平面修饰符",
    "Golden Publishing": "金色出版",
    "Guild Information": "公会信息",
    "Guild": "公会",
    "Guess the Word in 5 Tries": "猜五次这个单词",
    "Unlocks wordle minigame. Each Auto Writer increases manually typed words production by 5%.": "解锁字兜小游戏。每个自动作家增加5%的手工输入单词产量。",
    "Value per keystroke when typing manually": "手动键入时每个按键的价值",
    "Warning: This action cannot be undone.": "警告：此操作无法撤消。",
    "When enabled, pressing space jumps to the next word even when there is a mistake.": "启用后，即使有错误，按空格键也会跳到下一个单词。",
    "Winning gives a buff and medals.": "获胜会获得奖励和奖牌。",
    "Yearly Typing Championships": "年度打字锦标赛",
    "You have double the chance of finding golden news": "你有双倍的机会找到黄金新闻",
    "You receive additional hints during Wordle challenges": "在世界挑战中你会收到额外的提示",
    "Your Guild": "你的公会",
    "Your buildings upgrade the tower's capabilities.": "你的建筑提升了塔的能力。",
    "Your guild provides special benefits based on your chosen specialization. Choose wisely as changing specializations has a cooldown period.": "你的公会会根据你选择的专业提供特殊的福利。要明智地选择，因为更改专业有一个冷却期。",
    "Your tower is under attack from all sides!": "你的塔正受到来自四面八方的攻击！",
    "Your typing speed is boosted by +10 WPM in the arena": "在竞技场上，你的打字速度每分钟提高10个单词",
    "Loading game files...": "加载游戏文件...",
    "Remember the sequence:": "记住顺序：",
    "Total Production": "总产量",
    "Typing Idle Game": "打字放置游戏",
    "Improves income from all buildings.": "提高所有建筑的收入。",
    "Gourmet Coffee Selection": "极品咖啡精选",
    "keystrokes": "按键",
    "Keyboard layout": "键盘布局",
    "Keystrokes)": "按键)",
    "Choose your preferred keyboard layout": "选择您喜欢的键盘布局",
    "Change the visual theme of the game": "变游戏的视觉主题",
    "Note: All themes except dark are obsolete (Not yet updated to new UI)": "注意：除了深色之外的所有主题都是过时的（尚未更新到新的UI）",
    "New game": "新游戏",
    "Normal": "正常",
    "Start Game": "开始游戏",
    "Start Race": "开始比赛",
    "Start Typing test": "开始打字测试",
    "Stock Market Information:": "股票市场资讯：",
    "Per Keystroke Value": "每次按键价值",
    "free": "免费",
    "huge": "巨大",
    "Profit:": "利润:",
    "Publishing guild (2x the chance of golden news)": "出版公会（2x黄金新闻的几率）",
    "Error loading textures: ReferenceError: TypeParticleSystem is not defined": "加载纹理时出错：ReferenceError: TypeParticleSystem未定义",
    "Owned:": "拥有:",
    "Owned": "拥有",
    "Okay": "好的",
    "Research new typing techniques.": "研究新的打字技术。",
    "Defend the planet from the alien invasion!": "保卫地球免受外星人入侵！",
    "Each Produces": "每个生产",
    "finger to type the next key.": "手指去输入下一个键。",
    "Forest Green": "森林绿",
    "Easy": "简单",
    "High-Pressure Espresso Machines": "高压浓缩咖啡机",
    "Hijack the connection by untangling all the nodes.": "通过解开所有节点来劫持连接。",
    "HP Sauce": "生命酱",
    "is in the word and in the correct position.": "在单词里和正确的位置。",
    "is in the word but in the wrong position.": "在单词里但是在错误的位置。",
    "is not in the word.": "没出现在单词里。",
    "Light Coffee": "浅咖啡色",
    "Local Typing Agency": "本地打字公司",
    "Manual Keystrokes": "手动按键",
    "Manual Keystrokes:": "手动按键:",
    "Match 13 or more of the same symbol to win big!": "匹配13个或更多相同的符号，以赢得大！",
    "Max multiplier = 10000x": "最大乘数 = 10000x",
    "Megasoft": "超级软件",
    "Memorize the sequence of numbers and then type them in.": "记住这些数字的顺序，然后把它们输入进去。",
    "Midnight Blue": "午夜之蓝",
    "Memory": "记忆",
    "No transactions recorded yet": "暂无交易记录",
    "N/A": "N/A",
    "Once you have hijacked the connection crack the password.": "一旦你劫持了连接，请破解密码。",
    "Payout table": "支出表",
    "Reward: 10-60 minutes of instant production.": "奖励：10-60分钟的即时生产。",
    "Select a Guild Task": "选择一个公会任务",
    "Select race difficulty ": "选择比赛难度 ",
    "Spin the slot machine and try to match the symbols!": "转动游戏机，试着匹配这些符号！",
    "Test your ability to recall events": "测试你回忆事件的能力",
    "Test your ability to recall numbers": "测试你回忆数字的能力",
    "Triples production from Cyber Cafes by perfecting the latte art craft.": "通过完善拉花工艺，将网吧的产量提高了3倍。",
    "Triples production from manually typed words.": "将手工输入的单词的生产提高3倍。",
    "Triples production from Typing Arenas.": "将打字竞技场的生产提高3倍。",
    "Unlocks 'Reports' button in the navbar. Each Printer increases all buildings income by 0.75%.": "解锁导航栏中的“报告”按钮。每台打印机使所有建筑收益增加0.75%。",
    "Use the keyboard to type the words on the alien ships to destroy them.": "用键盘在外星飞船上输入单词以摧毁它们。",
    "Value": "价值",
    "Volume": "音量",
    "Wordle guild (Additional wordle hint)": "字兜公会（额外的世界提示）",
    "words)": "单词)",
    "You can print keystrokes?": "你可以打印按键？",
    "Opponent's Progress:": "对手进度：",
    "Printer Boost:": "打印机提升:",
    "Stats": "统计",
    "Symbol": "符号",
    "Memorize the details of a story.": "记住一个故事的细节。",
    "Level:": "等级:",
    "\"3D printers can create three-dimensional objects from digital models.\"": "“3D打印机可以从数字模型中创造出三维物体。“",
    "\"Algorithms that predict market trends with high accuracy.\"": "“高精度预测市场趋势的算法。”",
    "\"Cloud servers are virtual servers running in a cloud computing environment.\"": "“云服务器是运行在云计算环境中的虚拟服务器。”",
    "\"Color printers use a combination of four colors to produce a wide range of colors.\"": "“彩色打印机使用四种颜色的组合来产生各种各样的颜色。“",
    "\"Cyber Cafes are always open.\"": "“网吧总是开着的。”",
    "\"From Americano to Macchiato, premium flavors keep visitors typing away!\"": "“从美式咖啡到玛奇朵，优质的口味让游客流连不去！”",
    "\"IT support that never sleeps, takes holidays or calls in sick.\"": "“从不睡觉、不休假、不请病假的IT支持。”",
    "\"Just like a real assistant, but without the coffee breaks.\"": "“就像一个真正的助理，只是没有喝咖啡的休息时间。”",
    "\"Keys may or may not be pressed at the same time.\"": "“键可以同时按下，也可以不同时按下。”",
    "\"Lab with more beakers.\"": "“实验室有更多的烧杯。”",
    "\"Laser printers use a laser to produce high-quality prints.\"": "“激光打印机使用激光来打印高质量的印刷品。“",
    "\"Mechanical keyboards are known for their tactile feedback and durability.\"": "“机械键盘以其触觉反馈和耐用性而闻名。”",
    "\"Only the best typists are allowed in the elite guild.\"": "“只有最好的打字员才被允许进入精英公会。”",
    "\"Quantum printers don't require ink or toner.\"": "“量子打印机不需要墨水或碳粉。”",
    "\"Qubits may or may not be in a superposition.\"": "“量子比特可能处于叠加状态，也可能不处于叠加状态。”",
    "\"RGB keyboards makes typing in the dark easier.\"": "“幻彩键盘使在黑暗中打字更容易。”",
    "\"Typing champions are crowned every year.\"": "“打字冠军每年都会加冕。”",
    "\"When the latte looks stunning, customers stay longer and type more!\"": "“当拿铁看起来很棒的时候，顾客呆的时间更长，打字的次数也更多！”",
    "\"When the shots are strong, customers type faster!\"": "“当镜头强烈时，顾客打字更快！”",
    "I remember the story": "我记得那个故事",
    "Out of guesses! The word was:": "没猜出来！这个词是：",
    "Try again!": "再次尝试!",
    "1$ = 1 second of passive keystroke income.": "1$= 1秒被动按键收入。",
    "3 or more bonus symbols grant free spins.": "3个或3个以上的奖励符号可以获得免费转动。",
    "Active Modifiers": "活跃修饰符",
    "Alien Invasion": "外星人入侵",
    "Arena": "竞技场",
    "Arena guild (+10 Passive WPM increase in the arena)": "竞技场公会（在竞技场+10被动每秒单词数）",
    "Auto Writer Boost:": "自动作家提升:",
    "Assistant": "助手",
    "Base Rate": "基础速率",
    "Bet: $": "赌注: $",
    "Example: They sat on the **** of the river.": "例子: 他们坐在河边的 ****.",
    "Hint: the land alongside or sloping down to a river or lake": "提示：靠近河流或湖泊的土地",
    "Error loading textures: [object Event]": "加载纹理错误：[object Event]",
    "Lab coat not included.": "实验服不包括在内。",
    "Provides free Wi-Fi and boosts offline production.": "提供免费Wi-Fi，促进离线生产。",
    "Regional Typing Office": "区域打字办公室",
    "Unlocks research system. Grants research points.": "解锁研究系统。授予研究点数。",
    "PlasticSeries": "塑料系列",
    "Arcade": "街机",
    "Associate": "联系",
    "Average WPM": "平均每分钟打字数量",
    "Azerty": "法语键盘",
    "Cyber Cafe": "网吧",
    "Hacked: $": "入侵: $",
    "I remember it": "我记得它",
    "Logifetch": "逻辑获取",
    "Pineapple": "菠萝",
    "Casino": "堵场",
    "Right Index": "右手食指",
    "Left Index": "左手食指",
    "Right Ring": "右手无名指",
    "Left Ring": "左手无名指",
    "Left Pinky": "左手小指",
    "Right Pinky": "右手小指",
    "Left Middle": "左手中指",
    "Right Middle": "右手中指",
    "R. Ring": "右无名指",
    "L. Ring": "左无名指",
    "R. Pinky": "右小指",
    "L. Pinky": "左小指",
    "R. Middle": "右中指",
    "L. Middle": "左中指",
    "L. Index": "左手食指",
    "R. Index": "右手食指",
    "Provides passive income to manual keystrokes.": "为手动按键提供被动收入。",
    "Hacker": "黑客",
    "\"You can print keystrokes? That's impressive!\"": "“你可以打印按键？”这是令人印象深刻的!\”",
    "Achievement Unlocked": "成就已解锁",
    "Each Server Farm adds 0.1% of passive income to manual keystrokes.": "每个服务器农场增加0.1%的被动收入给手动按键。",
    "Free Wi-Fi included.": "包括免费Wi-Fi。",
    "Welcome back!": "欢迎回来！",
    "Server Boost:": "服务器提升:",
    "Supervisor": "主管",
    "Smell": "Smell",
    "Nationwide Typing Firm": "全国打字公司",
    "Increases offline keystroke production.": "提高离线按键生产。",
    "It's not a real farm.": "它不是一个真实的农场。",
    "Compete in typing races and earn buffs based on your performance.": "参加打字比赛，并根据你的表现获得增益。",
    "Unlocks 'Arena' button in the navbar.": "解锁导航栏中的“竞技场”按钮。",
    "Trophy Boost:": "奖杯提升：",
    "No, you can't use autocorrect.": "不，你不能使用自动纠错。",
    "Buildings cost less with each IT Office.": "每个IT办公室的建筑成本更低。",
    "Invest keystrokes in the stock market.": "在股票市场上进行按键投资。",
    "You lost!": "你输了！",
    "You won!": "你赢了！",
    "Auto Writers and manually typed words boosted by 100%. Manual keystrokes gain 1% of your passive income.": "自动作家和手动输入的单词提高了100%。手动按键获得1%你的被动收入。",
    "Magazine Publisher": "杂志出版商",
    "Promoted to Manager": "晋升为经理",
    "Publishes typing magazines.": "出版打字杂志。",
    "Sell Stocks": "出售股票",
    "Unlocks 'Stock Market' button in the navbar.": "解锁导航栏中的“股票市场”按钮。",
    "Continental Typing Corp": "大陆造船公司",
    "Manager": "经理",
    "Manual keystrokes boosted by 1% of passive income.": "手动按键增加被动收入的1%。",
    "Setup a guild of typing enthusiasts.": "成立一个打字爱好者公会。",
    "The only magazine about typing.": "唯一一本关于打字的杂志。",
    "Tip: Practice typing regularly to improve your speed and accuracy.": "提示：经常练习打字来提高你的速度和准确性。",
    "Fun Fact: The quick brown fox jumps over the lazy dog uses every letter in the English alphabet.": "有趣的事实：敏捷的棕色狐狸跳过了懒惰的狗，使用了英语字母表中的每一个字母。",
    "Publishes news every 20 seconds. Some news are golden. Clicking on golden news gives a temporary boost.": "每20秒发布一次新闻。有些新闻很有价值。点击黄金新闻会带来暂时的提升。",
    "Tip: Maintain a proper posture to avoid strain while typing.": "提示：打字时保持适当的姿势，避免紧张。",
    "Tip: Use a comfortable chair to maintain good posture while typing.": "Tip: Use a comfortable chair to maintain good posture while typing.",
    "Why did the computer keep freezing? It left its Windows open.": "为什么电脑一直冻着？它把窗户打开了。",
    "eBay is so useless. I tried to look up lighters and all they had was 13,749 matches.": "eBay太没用了。我试着找打火机，但他们只有13,749根火柴。",
    "Tip: Take regular breaks to avoid fatigue while typing.": "提示：打字时要有规律地休息，避免疲劳。",
    "Why do Java developers wear glasses? Because they don't C#.": "为什么Java开发人员要戴眼镜？因为他们不使用c#。",
    "New trend: Typing races becoming the latest e-sport sensation.": "新趋势：打字比赛成为最新的电子竞技轰动。",
    "Why don't keyboards ever sleep? Because they have two shifts.": "为什么键盘永远不会睡觉？因为他们有两班倒（2个Shift）。",
    "Breaking News: Local man types so fast, his keyboard starts smoking.": "突发新闻：一个当地人打字速度太快，键盘都冒烟了。",
    "Typing tip: Always keep your wrists straight to avoid carpal tunnel syndrome.": "打字提示：手腕要伸直，以免患上腕管综合症。",
    "Study shows that typing with two fingers is 50% less efficient than using all ten.": "研究表明，用两个手指打字的效率比用十个手指打字的效率低50%。",
    "Breaking News: New typing software claims to improve typing speed by 50%.": "突发新闻：新的打字软件声称能将打字速度提高50%。",
    "Breaking: Typing competitions now offering scholarships for the fastest typists.": "突发新闻：打字比赛现在为打字速度最快的人提供奖学金。",
    "Did you know? The average person types between 38 and 40 words per minute.": "你知道吗？人平均每分钟打38到40个单词。",
    "Fun Fact: The QWERTY keyboard layout was designed to prevent jamming on mechanical typewriters.": "有趣的事实：QWERTY键盘的布局是为了防止机械打字机的干扰。",
    "Fun Fact: The word 'typewriter' can be typed using only the top row of a QWERTY keyboard.": "有趣的事实：“typewriter”这个词只能在QWERTY键盘的最上面一排输入。",
    "Scientists discover that typing faster actually burns more calories.": "科学家发现打字越快，消耗的卡路里越多。",
    "Study: Typing games can help improve your typing speed and accuracy.": "研究：打字游戏可以帮助提高你的打字速度和准确性。",
    "What do you call a computer that sings? A-Dell.": "会唱歌的电脑叫什么？戴尔。",
    "Why do programmers prefer dark mode? Because light attracts bugs.": "为什么程序员更喜欢暗模式？因为光会吸引虫子。",
    "Why don't programmers like nature? It has too many bugs.": "为什么程序员不喜欢大自然？它有太多的bug。",
    "Why was the computer tired when it got home? It had a hard drive.": "为什么电脑回家时累了？它有一个硬盘驱动器。",
    "Why was the JavaScript developer sad? Because he didn't know how to 'null' his feelings.": "为什么JavaScript开发者会难过？因为他不知道如何“消除”自己的感觉。",
    "Unlocks 'Guild' button in the navbar.": "解锁导航栏中的“公会”按钮。",
    "Guild meetings are held in the Typing Arena.": "公会会议在打字竞技场举行。",
    "Error loading textures: TypeError: Cannot set properties of null (setting 'textContent')": "加载纹理时出错：TypeError：不能设置null属性（设置‘textContent’）",
    "Newcomer": "新人",
    "Hobby Typing": "爱好打字",
    "Hint: a piece of furniture with a flat top and one or more legs, providing a level surface on which objects may be placed": "提示: 一种有平顶和一条或多条腿的家具，提供一个可以放置物体的水平表面",
    "Promoted to Apprentice": "晋升为学徒",
    "\"You're just getting started!\"": "“你才刚刚开始！”",
    "\"You must really like typing!\"": "“你一定很喜欢打字！”",
    "Apprentice": "学徒",
    "Example: They sat around the ***** for dinner.": "例子: 他们坐在 ***** 吃晚饭。",
    "Neighborhood Typing Booth": "社区打字亭",
    "\"You're a typing gladiator!\"": "“你是打字高手！”",
    "Have you tried turning it off and on again?": "你试过关机再开机吗？",
    "Decreases the cost of all buildings by 0.5%. (Capped at 20%)": "降低所有建筑的成本0.5%。（上限为20%）",
    "\"One down, many more to go!\"": "“干掉一个，还有更多！”",
    "Example: He gave her a ***** of cake.": "例子:他给了她一个 ***** 的蛋糕。",
    "Hint: a portion of an object or of material, produced by cutting, tearing, or breaking the whole": "提示：通过切割、撕裂或破坏整体而产生的物体或材料的一部分",
    "\"Zettabytes of data!\"": "“zttabytes的数据！”",
    "\"Quickest internet in town!\"": "“城里最快的网络！”",
    "Error loading textures: SyntaxError: Expected ',' or ']' after array element in JSON at position 4106 (line 1 column 4107)": "错误加载纹理：SyntaxError：预期的‘,’或‘]’后的数组元素在JSON中的位置4106（第1行列4107）",
    "\"e=mc^2\"": "\"e=mc^2\"",
    "\"Gotta catch 'em all!\"": "“一定要把他们全抓起来！”",
    "\"Soon, you'll have an army of Auto Writers!\"": "“很快，你就会拥有一支自动作家大军！”",
    "\"Starting a small business.\"": "“开始做小生意。”",
    "\"You're running a printing empire!\"": "“你经营着一个印刷帝国！”",
    "Hint: move through the air using wings": "提示：用翅膀在空中移动",
    "Coarseair": "粗糙空气",
    "\"First step to becoming a stock market mogul!\"": "“成为股市大亨的第一步！”\”",
    "Advanced research labs:": "高级研究实验室：",
    "AI Typing Assistants:": "AI打字助手：",
    "Gourmet Coffee Selection:": "极品咖啡精选：",
    "Hacker Group": "黑客组织",
    "High-Pressure Espresso Machines:": "高压浓缩咖啡机：",
    "Purchased 1 shares": "购入1股",
    "Recruit hackers to help your keystroke business.": "招募黑客来帮助你的击键业务。",
    "Republican": "共和党",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    // 图标代码，不能汉化
    "Jacorb's Games": "Jacorb's Games",
    "YouTube": "YouTube",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "GitHub": "GitHub",
    "+": "+",
    ".": ".",
    "…": "…",
    ":": ":",
    "-": "-",
    "|": "|",
    "(": "(",
    ")": ")",
    "Scientific": "科学计数法",
    "Standard": "标准",
    "Blind": "盲文",
    "Letters": "字母",
    "Mixed Engineering": "混合工程",
    "Mixed Scientific": "混合科学",
    "Chemistry": "化学",
    "Engineering": "工程符号",
    "By Jacorb90": "By Jacorb90",
    "content_copy": "content_copy",
    "library_books": "library_books",
    "discord": "discord",
    "drag_handle": "drag_handle",
    "edit": "edit",
    "forum": "forum",
    "content_paste": "content_paste",
    "delete": "delete",
    "info": "info",
    "settings": "settings",
    'Twitter': 'Twitter',
    "Discord": "Discord",
    "Facebook": "Facebook",
    "Instagram": "Instagram",
    "gityxcom": "gityxcom",
    "Footer": "Footer",
    "Wiki": "Wiki",
    "gityx": "gityx",

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '打开',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    "Loading... (If this takes too long it means there was a serious error!": "正在加载...（如果这花费的时间太长，则表示存在严重错误！",
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    'Git游戏': 'Git游戏',
    'QQ群号': 'QQ群号',
    'x': 'x',
    'QQ群号:': 'QQ群号:',
    '* 启用后台游戏': '* 启用后台游戏',
    '更多同类游戏:': '更多同类游戏:',
    'i': 'i',
    'I': 'I',
    'II': 'II',
    'III': 'III',
    'IV': 'IV',
    'V': 'V',
    'VI': 'VI',
    'VII': 'VII',
    'VIII': 'VIII',
    'X': 'X',
    'XI': 'XI',
    'XII': 'XII',
    'XIII': 'XIII',
    'XIV': 'XIV',
    'XV': 'XV',
    'XVI': 'XVI',
    'A': 'A',
    'B': 'B',
    'C': 'C',
    'D': 'D',
    'E': 'E',
    'F': 'F',
    'G': 'G',
    'H': 'H',
    'I': 'I',
    'J': 'J',
    'K': 'K',
    'L': 'L',
    'M': 'M',
    'N': 'N',
    'O': 'O',
    'P': 'P',
    'Q': 'Q',
    'R': 'R',
    'S': 'S',
    'T': 'T',
    'U': 'U',
    'V': 'V',
    'W': 'W',
    'X': 'X',
    'Y': 'Y',
    'Z': 'Z',
    '<': '<',
    '<<': '<<',
    '>': '>',
    '>>': '>>',
    'Jan': '1月',
    'Feb': '2月',
    'Mar': '3月',
    'Apr': '4月',
    'May': '5月',
    'Jun': '6月',
    'Jul': '7月',
    'Aug': '8月',
    'Sep': '9月',
    'Oct': '10月',
    'Nov': '11月',
    'Dec': '12月',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',

}


//需处理的前缀，此处可以截取语句开头部分的内容进行汉化
//例如：Coin: 13、Coin: 14、Coin: 15... 这种有相同开头的语句
//可以在这里汉化开头："Coin: ":"金币: "
var cnPrefix = {
    "\n": "\n",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": " ",
    " ": " ",
    //树游戏
    "\t\t\t": "\t\t\t",
    "\n\n\t\t": "\n\n\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式：",
    "In-line Exponent: ": "直列指数：",
    "Single-Tab Mode: ": "单标签模式：",
    "Time Played: ": "已玩时长：",
    "Shift-Click to Toggle Tooltips: ": "Shift-单击以切换工具提示：",
    "Notation: ": "符号: ",
    "Toggle Music: ": "切换声音: ",
    "Loading textures...": "纹理加载中... ",
    "Buy Feature ": "购买功能 ",
    "Buy ": "购买 ",
    "Win: $": "胜: $",
    "Achievements: ": "成就: ",
    "Bonus game ": "奖励游戏 ",
    "Chance of Entering Bonus: ": "进入概率加成：",
    "Perfect: ": "完美: ",
    "Value (": "价值 (",
    "Start Hijack - ": "开始劫持 -",
    "Arcade - ": "街机 - ",
    "RGB Keyboards": "炫彩键盘",
    "Cloud Servers": "云服务器",
    "Color Printer": "彩色打印机",
    "Cooler Blaster": "冷却器导火线",
    "Cyberpunk Neon": "赛博朋克霓虹灯",
    "Mechanical Keyboards": "机械键盘",
    "Offline Earnings": "离线收益",
    "Publishing Guild": "出版公会",
    "Quantum Keyboards": "量子键盘",
    "Quantum Printers": "量子打印机",
    "Quantum Servers": "量子服务器",
    "Laser Printer": "激光打印机",
    "Your WPM: ": "你每分钟打字数量: ",
    "Champion of the Arena": "竞技场冠军",
    "3D Printer": "3D 打印机",
    "Correct! Boost activated! Doubled production from Auto Writers and manually typed words": "答对了！提升已激活！从自动作家和手动输入单词的产量翻倍",
    "Wordle Boost": "字兜提升",
    "Total: $": "总计: $",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀，此处可以截取语句结尾部分的内容进行汉化
//例如：13 Coin、14 Coin、15 Coin... 这种有相同结尾的语句
//可以在这里汉化结尾：" Coin":" 金币"
var cnPostfix = {
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "  ",
    " ": " ",
    "\n": "\n",
    "\n\t\t\t": "\n\t\t\t",
    "\t\t\n\t\t": "\t\t\n\t\t",
    "\t\t\t\t": "\t\t\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "/sec)": "/秒)",
    ' I': ' I',
    ' II': ' II',
    ' III': ' III',
    ' IV': ' IV',
    ' V': ' V',
    ' VI': ' VI',
    ' VII': ' VII',
    ' VIII': ' VIII',
    ' X': ' X',
    ' XI': ' XI',
    ' XII': ' XII',
    ' XIII': ' XIII',
    ' XIV': ' XIV',
    ' XV': ' XV',
    ' XVI': ' XVI',
    "x Streak!": "x 连胜!",
    " = BONUS": " = 奖励",
    "% of passive income)": "% 被动收入)",
    " from Cyber Cafes!": "从网吧！",
    " keystrokes)": " 按键)",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^\s*$/, //纯空格
    /^([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)h$/,
    /^([\d\.]+)m$/,
    /^([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)y ([\d\.]+)d ([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)y ([\d\.]+)d ([\d\.]+)h$/,
    /^([\d\.]+)\-([\d\.]+)\-([\d\.]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)$/,
    /^×([\d\.]+)$/,
    /^x([\d\.]+)$/,
    /^v([\d\.]+)$/,
    /^\$([\d\.]+)$/,
    /^\(([\d\.]+)\)$/,
    /^([\d\.]+)\%$/,
    /^\+([\d\.]+)\%$/,
    /^\+([\d\.]+) \(([\d\.]+)$/,
    /^\+([\d\.]+) k \(([\d\.]+)$/,
    /^([\d\.]+)\/([\d\.]+)$/,
    /^([\d\.]+)\/([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.,]+)$/,
    /^\(([\d\.]+)\/([\d\.]+)\)$/,
    /^ \(([\d\.]+)\/([\d\.]+)\)$/,
    /^成本(.+)$/,
    /^\(([\d\.]+)\%\)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)K$/,
    /^([\d\.]+)M$/,
    /^([\d\.]+)B$/,
    /^([\d\.]+) K$/,
    /^([\d\.]+) k$/,
    /^\+([\d\.]+) k$/,
    /^([\d\.]+) M$/,
    /^([\d\.]+) million$/,
    /^([\d\.]+) million\}$/,
    /^([\d\.]+) B$/,
    /^([\d\.]+) billion$/,
    /^([\d\.]+) billion\}$/,
    /^([\d\.]+) T$/,
    /^([\d\.]+) trillion\}$/,
    /^([\d\.]+) Qi$/,
    /^([\d\.]+) Qa$/,
    /^([\d\.]+) Sp$/,
    /^([\d\.]+) Oc$/,
    /^([\d\.]+) Dc$/,
    /^([\d\.]+) UDc$/,
    /^([\d\.]+) No$/,
    /^([\d\.]+) Sx$/,
    /^([\d\.]+) QaDc$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)x$/,
    /^x([\d\.]+)$/,
    /^([\d\.,]+)$/,
    /^\$([\d\.,]+)$/,
    /^\+([\d\.,]+)$/,
    /^\-([\d\.,]+)$/,
    /^([\d\.,]+)x$/,
    /^x([\d\.,]+)$/,
    /^×([\d\.,]+)$/,
    /^([\d\.,]+) \/ ([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+) \/ ([\d\.]+)e([\d\.,]+)$/,
    /^\$([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e\+([\d\.,]+)$/,
    /^e([\d\.]+)e([\d\.,]+)$/,
    /^x([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)x$/,
    /^([\uD800-\uDBFF][\uDC00-\uDFFF])|([\u2600-\u27BF])|([\u2300-\u23FF])|([\u2B50-\u2B55])|([\u203C-\u3299])|[\u21A9\u21AA\u25B6\u25C0\u2B06\u2B07\u2B05\u2B95\u2B99\u2B9A]+$/,
    // /^([\uD800-\uDBFF][\uDC00-\uDFFF])|([\u2600-\u27BF])|([\u2300-\u23FF])|([\u2B50-\u2B55])|([\u203C-\u3299])+$/,
    // /^[\uD800-\uFFFF]+$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//字母加数字：([\d\.]+[A-Za-z])
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
//&nbsp;空格：\xA0
var cnRegReplace = new Map([
    [/^([\d\.]+) hours ([\d\.]+) minutes ([\d\.]+) seconds$/, '$1 小时 $2 分钟 $3 秒'],
    [/^You are gaining (.+) elves per second$/, '你每秒获得 $1 精灵'],
    [/^\(Your WPM: (.+), Opponent WPM: (.+)\)$/, '(你的每分钟打字数量: $1, 对手每分钟打字数量: $2)'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
    [/^Sell (.+) stocks for (.+)$/, '出售 $1 股票获得 $2'],
    [/^(.+) stocks at (.+)$/, '$1 股票花费 $2'],
    [/^Reach (.+) keystrokes.$/, '达到 $1 次按键.'],
    [/^Solve (.+) Wordle puzzle.$/, '解决 $1 个字兜谜题.'],
    [/^Solve (.+) Wordle puzzles.$/, '解决 $1 个字兜谜题.'],
    [/^Own (.+) Printers.$/, '拥有 $1 打印机.'],
    [/^Own (.+) Server Farms.$/, '拥有 $1 服务器农场.'],
    [/^Own (.+) Cyber Cafes.$/, '拥有 $1 网吧.'],
    [/^Own (.+) Auto Writers.$/, '拥有 $1 自动作家.'],
    [/^\-\n(.+)Last updated (.+)$/, '-\n$1最近更新于 $2'],
    [/^Unlocks at (.+) total keystrokes.$/, '解锁于 $1 次按键总数.'],
    [/^Jan ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 1 月 $1, $3:$4'],
    [/^Feb ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 2 月 $1, $3:$4'],
    [/^Mar ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 3 月 $1, $3:$4'],
    [/^Apr ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 4 月 $1, $3:$4'],
    [/^May ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 5 月 $1, $3:$4'],
    [/^Jun ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 6 月 $1, $3:$4'],
    [/^Jul ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 7 月 $1, $3:$4'],
    [/^Aug ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 8 月 $1, $3:$4'],
    [/^Sep ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 9 月 $1, $3:$4'],
    [/^Oct ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 10 月 $1, $3:$4'],
    [/^Nov ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 11 月 $1, $3:$4'],
    [/^Dec ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 12 月 $1, $3:$4'],
	[/^([\d\.]+)\/sec$/, '$1\/秒'],
	[/^(.+)\/key$/, '$1\/键'],
	[/^(.+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+)\/([\d\.,]+) Cyber Cafes$/, '$1\/$2 网吧'],
	[/^([\d\.,]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+)e([\d\.,]+)\/sec$/, '$1e$2\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^([\d\.]+)e([\d\.,]+) points$/, '$1e$2 点数'],
    [/^([\d\.]+) elves$/, '$1 精灵'],
    [/^([\d\.]+)\/s$/, '$1\/秒'],
    [/^([\d\.]+) k\/s$/, '$1 k\/秒'],
    [/^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m$/, '$1天 $2小时 $3分'],
    [/^([\d\.]+)e([\d\.,]+) elves$/, '$1e$2 精灵'],
    [/^([\d\.,]+) elves$/, '$1 精灵'],
    [/^([\d\.,]+) Minute typing test$/, '$1 分钟打字测试'],
    [/^\/([\d\.,]+) keystrokes$/, '/$1 按键'],
    [/^([\d\.,]+)x \((.+)\)$/, '$1x ($1)'],
    [/^You can play again in: ([\d\.,]+)s$/, '你可以再玩一次，还需要等待：$1 秒'],
    [/^Boost remaining: ([\d\.,]+)s$/, '提升剩余时间: $1 秒'],
    [/^Day ([\d\.,]+)$/, '天数 $1'],
    [/^Lvl. ([\d\.,]+)$/, '等级 $1'],
    [/^Lvl ([\d\.,]+)$/, '等级 $1'],
    [/^Level ([\d\.,]+)$/, '等级 $1'],
    [/^level ([\d\.,]+) \/ ([\d\.,]+)$/, '等级 $1 \/ $2'],
    [/^level: ([\d\.,]+) \/ ([\d\.,]+)$/, '等级 $1 \/ $2'],
    [/^\*(.+) to electricity gain$/, '\*$1 到电力增益'],
    [/^Cost: (.+) points$/, '成本：$1 点数'],
    [/^Req: (.+) elves$/, '要求：$1 精灵'],
    [/^Req: (.+) \/ (.+) elves$/, '要求：$1 \/ $2 精灵'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);